import { SiteInfo } from "./site-info.js";

export default [
	new SiteInfo({
		id: 401,
		name: "Imgur",
		description: "2ch民定番の画像アップローダー",
		src: "https://imgur.com/WKkpmbf",
		hostnames: ["i.imgur.com"],
		href: "https://imguruploader.com",
	}),
	new SiteInfo({
		id: 404,
		name: "アル",
		description: "マンガのコマを著作権を気にせず貼り付けられるサービス",
		src: "https://alu.jp/series/SPY%C3%97FAMILY/crop/TRTV4HvxzlBMUpNYcwp9",
		href: "https://alu.jp/cropSearch?q=%E3%83%AC%E3%82%B9%E3%81%AB%E4%BD%BF%E3%81%88%E3%82%8B%E3%82%B3%E3%83%9E",
	}),
	new SiteInfo({
		id: 411,
		name: "よねっと",
		description: "ふなかもめ本体",
		src: "https://funakamome.com/i/eyIK6PE.png",
		href: "https://funakamome.com/imgurup",
	}),
	new SiteInfo({
		id: 412,
		name: "imgx",
		description: "よねっと経由でうｐ可能その1",
		src: "https://imgx.site/i/3q9sMTX.png",
		href: "https://funakamome.com/imgurup",
	}),
	new SiteInfo({
		id: 413,
		name: "ImgBB",
		description: "よねっと経由でうｐ可能その2",
		src: "https://i.ibb.co/Xxk61hsb/2025-06-25-212016.png",
		href: "https://funakamome.com/imgurup",
		favicon: "imgbb.com",
	}),
	new SiteInfo({
		id: 402,
		name: "ニコニコ静画",
		description: "『静止画』サービスの総合サイト",
		src: "https://seiga.nicovideo.jp/seiga/im11532584",
		hostnames: ["sp.seiga.nicovideo.jp"],
	}),
	new SiteInfo({
		id: 403,
		name: "Pixiv",
		description: "イラスト・マンガ・小説コミュニティサイト",
		src: "https://www.pixiv.net/artworks/120257879",
	}),
	new SiteInfo({
		id: 405,
		name: "Feeder",
		description: "2010年誕生の、基本無料で使える多機能Webチャット🐱",
		src: "https://www2.x-feeder.info/unjupiter/pictures/PIC_EqbZ2y.png",
		hostnames: ["www1.x-feeder.info"],
		href: "https://www2.x-feeder.info/gZYDuRRm",
	}),
	new SiteInfo({
		id: 421,
		name: "Cloudflare R2",
		description: "10GBまで無料のストレージ",
		src: "https://pub-d049c945dab44db6b75372fdf9cb8401.r2.dev/8f7e7ab1-aae4-4f78-ba52-5ee5785a142b.png",
		href: "https://www.cloudflare.com/ja-jp/developer-platform/products/r2/",
		favicon: "www.cloudflare.com",
	}),
	new SiteInfo({
		id: 422,
		name: "Cloudflare R2",
		description: "10GBまで無料のストレージ",
		src: "https://pub-1bb6b377333b47d180596c0756cc5fe2.r2.dev/1785176594657-7su1gu.png",
		href: "https://www.cloudflare.com/ja-jp/developer-platform/products/r2/",
		favicon: "www.cloudflare.com",
	}),
	new SiteInfo({
		id: 431,
		name: "画像うｐろだつくってみた",
		description: "（注：消す機能まだ）",
		src: "https://imgu.jp/i/7e8a4213Ir.png",
		favicon: "hayabusa.open2ch.net",
	}),
];
